version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           apt update -y
           apt-get -y update && apt-get -y upgrade && apt-get -y install zip zipalign bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi python2 cpio
           git clone https://github.com/zclkkk/msm-4.14.git --depth=1 -b test
           git clone https://github.com/wloot/raphael --depth=1
           mv linux-x86/clang-r428724 clang
           rm -rf linux-x86
           BOARD=raphael
           git clone --depth=1 https://github.com/zclkkk/AnyKernel3 -b main
           CLANG_DIR=../clang
           export KBUILD_BUILD_USER="mudada"
           export KBUILD_BUILD_HOST="TestKernel"
           args="O=../out ARCH=arm64 CC=${CLANG_DIR}/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LD=${CLANG_DIR}/bin/ld.lld"
           cd msm-4.14
           make ${args} ${BOARD}_defconfig
           make -j16 ${args}
           cd ..
           cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
           cp out/arch/arm64/boot/dtbo.img AnyKernel3/
           cd AnyKernel3
           VERSION="$(cat ../msm-4./arch/arm64/configs/${BOARD}_defconfig | grep "CONFIG_LOCALVERSION\=" | sed -r 's/.*"(.+)".*/\1/' | sed 's/^.//')"
           VERSION=TadaKernel_BETA
           7z a -mx9 ${VERSION}.zip *
           zipalign -v 4 ${VERSION}.zip ../${VERSION}_${BOARD}.zip
           cd ..
           curl -sL https://git.io/file-transfer | bash -s beta
           ./transfer gof ${VERSION}_${BOARD}.zip
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
